[package]
name = "inter_stage"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
