[workspace]
members = [
    "generic",
    "lifetime",
    "macro_stu",
    "own",
    "package_mod",
    "smart_pointer",
    "study_clap",
    "trait_stu",
    "base_stu",
]
resolver = "2"


[workspace.dependencies]
